fail_fast: true
repos:
  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black
        name: black
        stages: [pre-commit]
        language_version: python3.11
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        stages: [pre-commit]
        types: [python]
        entry: pylint
        language: system
        pass_filenames: true
        args: ["--jobs=4"]
      - id: pytest
        name: pytest
        stages: [pre-commit]
        types: [python]
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ["--exitfirst", "-n", "auto"]
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        stages: [pre-commit]
        types: [python]
        entry: pyright
        language: system
        pass_filenames: false
        always_run: true
        args: [--threads=8]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: mixed-line-ending
        args: [--fix=no]
