fail_fast: true
repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        stages: [pre-commit]
        types: [python]
        entry: uv run --frozen ruff format
        language: system
      - id: ruff-check
        name: ruff check
        stages: [pre-commit]
        types: [python]
        entry: uv run --frozen ruff check --fix
        language: system
      - id: pytest
        name: pytest
        stages: [pre-commit]
        types: [python]
        entry: uv run --frozen pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ["--exitfirst", "-n", "auto"]
      - id: pyright
        name: pyright
        stages: [pre-commit]
        types: [python]
        entry: uv run --frozen pyright
        language: system
        pass_filenames: false
        always_run: true
        args: [--threads=8]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: mixed-line-ending
        args: [--fix=no]
